// yarn.lock parsing: classic v1 and the Yarn Berry YAML flavor.
import { test } from "node:test";
import { strict as assert } from "node:assert";
import { parseYarnLock } from "../dist/index.js";

const V1_HEADER = "# THIS IS AN AUTOGENERATED FILE.\n# yarn lockfile v1\n\n";

test("parses classic v1 entries", () => {
  const snap = parseYarnLock(
    V1_HEADER +
      'ansi-mist@^1.0.0:\n  version "1.0.4"\n  resolved "https://registry.example.test/x.tgz"\n\n' +
      '"@demo/router@^3.1.0":\n  version "3.1.0"\n',
  );
  assert.equal(snap.format, "yarn");
  assert.deepEqual(snap.packages.get("ansi-mist"), ["1.0.4"]);
  assert.deepEqual(snap.packages.get("@demo/router"), ["3.1.0"]);
});

test("multi-selector headers record the version once per package", () => {
  const snap = parseYarnLock(
    V1_HEADER + 'tarline@^2.0.0, tarline@^2.0.2, "tarline@>=2":\n  version "2.0.3"\n',
  );
  assert.deepEqual(snap.packages.get("tarline"), ["2.0.3"]);
});

test("the same package resolved twice yields a sorted version set", () => {
  const snap = parseYarnLock(
    V1_HEADER + 'left-pad@^2.0.0:\n  version "2.1.0"\n\nleft-pad@^1.0.0:\n  version "1.3.0"\n',
  );
  assert.deepEqual(snap.packages.get("left-pad"), ["1.3.0", "2.1.0"]);
});

test("parses Berry YAML entries (npm: protocol, unquoted version)", () => {
  const berry =
    "__metadata:\n  version: 8\n  cacheKey: 10\n\n" +
    '"quicklog@npm:^2.4.0":\n  version: 2.4.3\n  resolution: "quicklog@npm:2.4.3"\n\n' +
    '"@demo/router@npm:^3.2.0":\n  version: 3.2.0\n';
  const snap = parseYarnLock(berry);
  assert.deepEqual(snap.packages.get("quicklog"), ["2.4.3"]);
  assert.deepEqual(snap.packages.get("@demo/router"), ["3.2.0"]);
  assert.equal(snap.packages.has("__metadata"), false);
});

test("skips workspace selectors and Berry's 0.0.0-use.local placeholder", () => {
  const berry =
    '"my-app@workspace:.":\n  version: 0.0.0-use.local\n\n' +
    '"real-dep@npm:^1.0.0":\n  version: 1.2.0\n';
  const snap = parseYarnLock(berry);
  assert.deepEqual([...snap.packages.keys()], ["real-dep"]);
});

test("selector commas inside quotes do not split entries", () => {
  // A range like ">=1.0.0, <2.0.0" contains a comma that must not create a
  // phantom selector.
  const snap = parseYarnLock(V1_HEADER + '"oddrange@>=1.0.0, <2.0.0":\n  version "1.5.0"\n');
  assert.deepEqual([...snap.packages.keys()], ["oddrange"]);
  assert.deepEqual(snap.packages.get("oddrange"), ["1.5.0"]);
});

test("rejects JSON bodies and entry-less non-lockfile text", () => {
  assert.throws(() => parseYarnLock('{"lockfileVersion":3}', "x.lock"), /looks like JSON/);
  assert.throws(() => parseYarnLock("just some prose\nwith two lines\n", "x.lock"), /no lockfile entries/);
  // An empty-but-marked v1 file is fine: zero packages is a valid state.
  const empty = parseYarnLock(V1_HEADER);
  assert.equal(empty.packages.size, 0);
});
